modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/MC-U-Team/Halloween-Luckyblocks/issues"
displayURL="https://u-team.info/mods/halloween_luckyblock"
logoFile="logo.png"
license="Apache-2.0 License"
credits="LuckyCrew and Team U Team"
authors="HyCraftHD, Nurenja, Milchbar, Redhair, Angelgaming"

[[mods]]
	modId="halloween_luckyblock"
	version="${file.jarVersion}"
	displayName="Halloween LuckyBlock"	updateJSONURL="https://api.u-team.info/update/halloween_luckyblock.json"
	description="Cool and spooky luckyblocks for halloween."
	
	[[dependencies.halloween_luckyblock]]
	    modId="forge"
	    mandatory=true
	    versionRange="[34.1.42,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.halloween_luckyblock]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.16.3]"
	    ordering="NONE"
	    side="BOTH"
	    
	[[dependencies.halloween_luckyblock]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="[3.1.12.185,)"
	    ordering="NONE"
	    side="BOTH"